# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/torster/Desktop/izip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/torster/Desktop/izip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"fmt-core\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/torster/Desktop/izip/CMakeFiles /home/torster/Desktop/izip//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/torster/Desktop/izip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named izip

# Build rule for target.
izip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 izip
.PHONY : izip

# fast build rule for target.
izip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/build
.PHONY : izip/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f fmt/CMakeFiles/fmt.dir/build.make fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f spdlog/CMakeFiles/spdlog.dir/build.make spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/Experimental.dir/build.make libarchive/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/Nightly.dir/build.make libarchive/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/Continuous.dir/build.make libarchive/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyMemoryCheck.dir/build.make libarchive/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyStart.dir/build.make libarchive/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyUpdate.dir/build.make libarchive/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyConfigure.dir/build.make libarchive/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyBuild.dir/build.make libarchive/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyTest.dir/build.make libarchive/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyCoverage.dir/build.make libarchive/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlyMemCheck.dir/build.make libarchive/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/NightlySubmit.dir/build.make libarchive/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalStart.dir/build.make libarchive/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalUpdate.dir/build.make libarchive/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalConfigure.dir/build.make libarchive/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalBuild.dir/build.make libarchive/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalTest.dir/build.make libarchive/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalCoverage.dir/build.make libarchive/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalMemCheck.dir/build.make libarchive/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ExperimentalSubmit.dir/build.make libarchive/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousStart.dir/build.make libarchive/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousUpdate.dir/build.make libarchive/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousConfigure.dir/build.make libarchive/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousBuild.dir/build.make libarchive/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousTest.dir/build.make libarchive/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousCoverage.dir/build.make libarchive/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousMemCheck.dir/build.make libarchive/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/ContinuousSubmit.dir/build.make libarchive/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named run_all_tests

# Build rule for target.
run_all_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_all_tests
.PHONY : run_all_tests

# fast build rule for target.
run_all_tests/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/CMakeFiles/run_all_tests.dir/build.make libarchive/CMakeFiles/run_all_tests.dir/build
.PHONY : run_all_tests/fast

#=============================================================================
# Target rules for targets named archive

# Build rule for target.
archive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive
.PHONY : archive

# fast build rule for target.
archive/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/libarchive/CMakeFiles/archive.dir/build.make libarchive/libarchive/CMakeFiles/archive.dir/build
.PHONY : archive/fast

#=============================================================================
# Target rules for targets named archive_static

# Build rule for target.
archive_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive_static
.PHONY : archive_static

# fast build rule for target.
archive_static/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/libarchive/CMakeFiles/archive_static.dir/build.make libarchive/libarchive/CMakeFiles/archive_static.dir/build
.PHONY : archive_static/fast

#=============================================================================
# Target rules for targets named libarchive_test

# Build rule for target.
libarchive_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libarchive_test
.PHONY : libarchive_test

# fast build rule for target.
libarchive_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/libarchive/test/CMakeFiles/libarchive_test.dir/build.make libarchive/libarchive/test/CMakeFiles/libarchive_test.dir/build
.PHONY : libarchive_test/fast

#=============================================================================
# Target rules for targets named run_libarchive_test

# Build rule for target.
run_libarchive_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_libarchive_test
.PHONY : run_libarchive_test

# fast build rule for target.
run_libarchive_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/libarchive/test/CMakeFiles/run_libarchive_test.dir/build.make libarchive/libarchive/test/CMakeFiles/run_libarchive_test.dir/build
.PHONY : run_libarchive_test/fast

#=============================================================================
# Target rules for targets named bsdcat

# Build rule for target.
bsdcat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdcat
.PHONY : bsdcat

# fast build rule for target.
bsdcat/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/cat/CMakeFiles/bsdcat.dir/build.make libarchive/cat/CMakeFiles/bsdcat.dir/build
.PHONY : bsdcat/fast

#=============================================================================
# Target rules for targets named bsdcat_test

# Build rule for target.
bsdcat_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdcat_test
.PHONY : bsdcat_test

# fast build rule for target.
bsdcat_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/cat/test/CMakeFiles/bsdcat_test.dir/build.make libarchive/cat/test/CMakeFiles/bsdcat_test.dir/build
.PHONY : bsdcat_test/fast

#=============================================================================
# Target rules for targets named run_bsdcat_test

# Build rule for target.
run_bsdcat_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_bsdcat_test
.PHONY : run_bsdcat_test

# fast build rule for target.
run_bsdcat_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/cat/test/CMakeFiles/run_bsdcat_test.dir/build.make libarchive/cat/test/CMakeFiles/run_bsdcat_test.dir/build
.PHONY : run_bsdcat_test/fast

#=============================================================================
# Target rules for targets named bsdtar

# Build rule for target.
bsdtar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdtar
.PHONY : bsdtar

# fast build rule for target.
bsdtar/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/tar/CMakeFiles/bsdtar.dir/build.make libarchive/tar/CMakeFiles/bsdtar.dir/build
.PHONY : bsdtar/fast

#=============================================================================
# Target rules for targets named bsdtar_test

# Build rule for target.
bsdtar_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdtar_test
.PHONY : bsdtar_test

# fast build rule for target.
bsdtar_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/tar/test/CMakeFiles/bsdtar_test.dir/build.make libarchive/tar/test/CMakeFiles/bsdtar_test.dir/build
.PHONY : bsdtar_test/fast

#=============================================================================
# Target rules for targets named run_bsdtar_test

# Build rule for target.
run_bsdtar_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_bsdtar_test
.PHONY : run_bsdtar_test

# fast build rule for target.
run_bsdtar_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/tar/test/CMakeFiles/run_bsdtar_test.dir/build.make libarchive/tar/test/CMakeFiles/run_bsdtar_test.dir/build
.PHONY : run_bsdtar_test/fast

#=============================================================================
# Target rules for targets named bsdcpio

# Build rule for target.
bsdcpio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdcpio
.PHONY : bsdcpio

# fast build rule for target.
bsdcpio/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/cpio/CMakeFiles/bsdcpio.dir/build.make libarchive/cpio/CMakeFiles/bsdcpio.dir/build
.PHONY : bsdcpio/fast

#=============================================================================
# Target rules for targets named bsdcpio_test

# Build rule for target.
bsdcpio_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdcpio_test
.PHONY : bsdcpio_test

# fast build rule for target.
bsdcpio_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/cpio/test/CMakeFiles/bsdcpio_test.dir/build.make libarchive/cpio/test/CMakeFiles/bsdcpio_test.dir/build
.PHONY : bsdcpio_test/fast

#=============================================================================
# Target rules for targets named run_bsdcpio_test

# Build rule for target.
run_bsdcpio_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_bsdcpio_test
.PHONY : run_bsdcpio_test

# fast build rule for target.
run_bsdcpio_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/cpio/test/CMakeFiles/run_bsdcpio_test.dir/build.make libarchive/cpio/test/CMakeFiles/run_bsdcpio_test.dir/build
.PHONY : run_bsdcpio_test/fast

#=============================================================================
# Target rules for targets named bsdunzip

# Build rule for target.
bsdunzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdunzip
.PHONY : bsdunzip

# fast build rule for target.
bsdunzip/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/unzip/CMakeFiles/bsdunzip.dir/build.make libarchive/unzip/CMakeFiles/bsdunzip.dir/build
.PHONY : bsdunzip/fast

#=============================================================================
# Target rules for targets named bsdunzip_test

# Build rule for target.
bsdunzip_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsdunzip_test
.PHONY : bsdunzip_test

# fast build rule for target.
bsdunzip_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/unzip/test/CMakeFiles/bsdunzip_test.dir/build.make libarchive/unzip/test/CMakeFiles/bsdunzip_test.dir/build
.PHONY : bsdunzip_test/fast

#=============================================================================
# Target rules for targets named run_bsdunzip_test

# Build rule for target.
run_bsdunzip_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_bsdunzip_test
.PHONY : run_bsdunzip_test

# fast build rule for target.
run_bsdunzip_test/fast:
	$(MAKE) $(MAKESILENT) -f libarchive/unzip/test/CMakeFiles/run_bsdunzip_test.dir/build.make libarchive/unzip/test/CMakeFiles/run_bsdunzip_test.dir/build
.PHONY : run_bsdunzip_test/fast

#=============================================================================
# Target rules for targets named CLI11

# Build rule for target.
CLI11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLI11
.PHONY : CLI11

# fast build rule for target.
CLI11/fast:
	$(MAKE) $(MAKESILENT) -f CLI11/src/CMakeFiles/CLI11.dir/build.make CLI11/src/CMakeFiles/CLI11.dir/build
.PHONY : CLI11/fast

source/App.o: source/App.cpp.o
.PHONY : source/App.o

# target to build an object file
source/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/App.cpp.o
.PHONY : source/App.cpp.o

source/App.i: source/App.cpp.i
.PHONY : source/App.i

# target to preprocess a source file
source/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/App.cpp.i
.PHONY : source/App.cpp.i

source/App.s: source/App.cpp.s
.PHONY : source/App.s

# target to generate assembly for a file
source/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/App.cpp.s
.PHONY : source/App.cpp.s

source/Appctor.o: source/Appctor.cpp.o
.PHONY : source/Appctor.o

# target to build an object file
source/Appctor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/Appctor.cpp.o
.PHONY : source/Appctor.cpp.o

source/Appctor.i: source/Appctor.cpp.i
.PHONY : source/Appctor.i

# target to preprocess a source file
source/Appctor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/Appctor.cpp.i
.PHONY : source/Appctor.cpp.i

source/Appctor.s: source/Appctor.cpp.s
.PHONY : source/Appctor.s

# target to generate assembly for a file
source/Appctor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/Appctor.cpp.s
.PHONY : source/Appctor.cpp.s

source/comp_file/File.o: source/comp_file/File.cpp.o
.PHONY : source/comp_file/File.o

# target to build an object file
source/comp_file/File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_file/File.cpp.o
.PHONY : source/comp_file/File.cpp.o

source/comp_file/File.i: source/comp_file/File.cpp.i
.PHONY : source/comp_file/File.i

# target to preprocess a source file
source/comp_file/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_file/File.cpp.i
.PHONY : source/comp_file/File.cpp.i

source/comp_file/File.s: source/comp_file/File.cpp.s
.PHONY : source/comp_file/File.s

# target to generate assembly for a file
source/comp_file/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_file/File.cpp.s
.PHONY : source/comp_file/File.cpp.s

source/comp_file/archive_computation.o: source/comp_file/archive_computation.cpp.o
.PHONY : source/comp_file/archive_computation.o

# target to build an object file
source/comp_file/archive_computation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_file/archive_computation.cpp.o
.PHONY : source/comp_file/archive_computation.cpp.o

source/comp_file/archive_computation.i: source/comp_file/archive_computation.cpp.i
.PHONY : source/comp_file/archive_computation.i

# target to preprocess a source file
source/comp_file/archive_computation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_file/archive_computation.cpp.i
.PHONY : source/comp_file/archive_computation.cpp.i

source/comp_file/archive_computation.s: source/comp_file/archive_computation.cpp.s
.PHONY : source/comp_file/archive_computation.s

# target to generate assembly for a file
source/comp_file/archive_computation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_file/archive_computation.cpp.s
.PHONY : source/comp_file/archive_computation.cpp.s

source/comp_help/Help.o: source/comp_help/Help.cpp.o
.PHONY : source/comp_help/Help.o

# target to build an object file
source/comp_help/Help.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_help/Help.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/source/comp_help/Help.cpp.o
.PHONY : source/comp_help/Help.cpp.o

source/comp_help/Help.i: source/comp_help/Help.cpp.i
.PHONY : source/comp_help/Help.i

# target to preprocess a source file
source/comp_help/Help.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_help/Help.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/source/comp_help/Help.cpp.i
.PHONY : source/comp_help/Help.cpp.i

source/comp_help/Help.s: source/comp_help/Help.cpp.s
.PHONY : source/comp_help/Help.s

# target to generate assembly for a file
source/comp_help/Help.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/comp_help/Help.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/source/comp_help/Help.cpp.s
.PHONY : source/comp_help/Help.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/izip.dir/build.make CMakeFiles/izip.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

test/comp_help/descriptors/general_message.o: test/comp_help/descriptors/general_message.cpp.o
.PHONY : test/comp_help/descriptors/general_message.o

# target to build an object file
test/comp_help/descriptors/general_message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/general_message.cpp.o
.PHONY : test/comp_help/descriptors/general_message.cpp.o

test/comp_help/descriptors/general_message.i: test/comp_help/descriptors/general_message.cpp.i
.PHONY : test/comp_help/descriptors/general_message.i

# target to preprocess a source file
test/comp_help/descriptors/general_message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/general_message.cpp.i
.PHONY : test/comp_help/descriptors/general_message.cpp.i

test/comp_help/descriptors/general_message.s: test/comp_help/descriptors/general_message.cpp.s
.PHONY : test/comp_help/descriptors/general_message.s

# target to generate assembly for a file
test/comp_help/descriptors/general_message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/general_message.cpp.s
.PHONY : test/comp_help/descriptors/general_message.cpp.s

test/comp_help/descriptors/param_descriptor.o: test/comp_help/descriptors/param_descriptor.cpp.o
.PHONY : test/comp_help/descriptors/param_descriptor.o

# target to build an object file
test/comp_help/descriptors/param_descriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/param_descriptor.cpp.o
.PHONY : test/comp_help/descriptors/param_descriptor.cpp.o

test/comp_help/descriptors/param_descriptor.i: test/comp_help/descriptors/param_descriptor.cpp.i
.PHONY : test/comp_help/descriptors/param_descriptor.i

# target to preprocess a source file
test/comp_help/descriptors/param_descriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/param_descriptor.cpp.i
.PHONY : test/comp_help/descriptors/param_descriptor.cpp.i

test/comp_help/descriptors/param_descriptor.s: test/comp_help/descriptors/param_descriptor.cpp.s
.PHONY : test/comp_help/descriptors/param_descriptor.s

# target to generate assembly for a file
test/comp_help/descriptors/param_descriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/param_descriptor.cpp.s
.PHONY : test/comp_help/descriptors/param_descriptor.cpp.s

test/comp_help/descriptors/param_help_descriptors.o: test/comp_help/descriptors/param_help_descriptors.cpp.o
.PHONY : test/comp_help/descriptors/param_help_descriptors.o

# target to build an object file
test/comp_help/descriptors/param_help_descriptors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/param_help_descriptors.cpp.o
.PHONY : test/comp_help/descriptors/param_help_descriptors.cpp.o

test/comp_help/descriptors/param_help_descriptors.i: test/comp_help/descriptors/param_help_descriptors.cpp.i
.PHONY : test/comp_help/descriptors/param_help_descriptors.i

# target to preprocess a source file
test/comp_help/descriptors/param_help_descriptors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/param_help_descriptors.cpp.i
.PHONY : test/comp_help/descriptors/param_help_descriptors.cpp.i

test/comp_help/descriptors/param_help_descriptors.s: test/comp_help/descriptors/param_help_descriptors.cpp.s
.PHONY : test/comp_help/descriptors/param_help_descriptors.s

# target to generate assembly for a file
test/comp_help/descriptors/param_help_descriptors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/comp_help/descriptors/param_help_descriptors.cpp.s
.PHONY : test/comp_help/descriptors/param_help_descriptors.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... run_all_tests"
	@echo "... run_bsdcat_test"
	@echo "... run_bsdcpio_test"
	@echo "... run_bsdtar_test"
	@echo "... run_bsdunzip_test"
	@echo "... run_libarchive_test"
	@echo "... CLI11"
	@echo "... archive"
	@echo "... archive_static"
	@echo "... bsdcat"
	@echo "... bsdcat_test"
	@echo "... bsdcpio"
	@echo "... bsdcpio_test"
	@echo "... bsdtar"
	@echo "... bsdtar_test"
	@echo "... bsdunzip"
	@echo "... bsdunzip_test"
	@echo "... fmt"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... izip"
	@echo "... libarchive_test"
	@echo "... spdlog"
	@echo "... test"
	@echo "... source/App.o"
	@echo "... source/App.i"
	@echo "... source/App.s"
	@echo "... source/Appctor.o"
	@echo "... source/Appctor.i"
	@echo "... source/Appctor.s"
	@echo "... source/comp_file/File.o"
	@echo "... source/comp_file/File.i"
	@echo "... source/comp_file/File.s"
	@echo "... source/comp_file/archive_computation.o"
	@echo "... source/comp_file/archive_computation.i"
	@echo "... source/comp_file/archive_computation.s"
	@echo "... source/comp_help/Help.o"
	@echo "... source/comp_help/Help.i"
	@echo "... source/comp_help/Help.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... test/comp_help/descriptors/general_message.o"
	@echo "... test/comp_help/descriptors/general_message.i"
	@echo "... test/comp_help/descriptors/general_message.s"
	@echo "... test/comp_help/descriptors/param_descriptor.o"
	@echo "... test/comp_help/descriptors/param_descriptor.i"
	@echo "... test/comp_help/descriptors/param_descriptor.s"
	@echo "... test/comp_help/descriptors/param_help_descriptors.o"
	@echo "... test/comp_help/descriptors/param_help_descriptors.i"
	@echo "... test/comp_help/descriptors/param_help_descriptors.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

