name: izip-workflow

on:
  - pull_request
  - push

env:
  runs-on: ubuntu-latest
  BUILD_TYPE: Debug

jobs:
  Initialize-dependenies:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          path: ${{github.workspace}}/fmt

      - name: "Configurating dependencies"
        run: git submodule update --init --recursive

  Generate-project-files:
    needs: "Initialize-dependenies"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}

      - name: Generate_project_files
        #cmake -B ${{github.workspace}}/build ${{github.workspace}}
        run: ls ${{github.workspace}}/fmt

  Build:
    needs: "Generate-project-files"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: cmake --build ${{github.workspace}}/build

  Execute:
    needs: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run program
        run: ${{github.workspace}}/build/izip -v

      - name: Run tests
        run: ${{github.workspace}}/build/test

  Tests:
    needs: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ${{github.workspace}}/build/test

