name: izip-workflow

on:
  - pull_request
  - push

env:
  runs-on: ubuntu-latest
  BUILD_TYPE: Debug
  paths:
    - .

jobs:
  Initialize-dependenies:
    runs-on: ubuntu-latest
    volumes:
      - .

    steps:
      - uses: actions/checkout@v4

      - name: configurating_dependencies
        run: git submodule update --init --recursive

    Generate-project-files:
      runs-on: ubuntu-latest
      volumes:
        - .

      steps:
        - uses: actions/checkout@v4

        - name: Generate_project_files
          run: cmake -B ${{github.workspace}}/build ${{github.workspace}}


    Build:
      runs-on: ubuntu-latest
      volumes:
        - .

      steps:
        - uses: actions/checkout@v4

        - name: Compile
          run: cmake --build ${{github.workspace}}/build

  Execute:
    runs-on: ubuntu-latest
    volumes:
      - .

    steps:
      - uses: actions/checkout@v4

      - name: Run program
        run: ${{github.workspace}}/build/izip -v

      - name: Run tests
        run: ${{github.workspace}}/build/test

  Tests:
    runs-on: ubuntu-latest
    volumes:
      - .

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ${{github.workspace}}/build/test

