name: izip-workflow

on:
  - pull_request
  - push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: configurating_dependencies
      run: git submodule update --init --recursive

    - name: Generate_project_files
      run: cmake -B ${{github.workspace}}/build ${{github.workspace}}

    - name: Compile
      run: cmake --build ${{github.workspace}}/build

    - name: Run program
      run: ${{github.workspace}}/build/izip

    - name: Run tests
      run: ${{github.workspace}}/build/test

