name: izip-workflow

on:
  - pull_request
  - push

env:
  runs-on: ubuntu-latest
  BUILD_TYPE: Debug

jobs:
  Initialize-dependenies:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
    paths:
      - .

      - name: "Configurating dependencies"
        run: git submodule update --init --recursive

    Generate-project-files:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
      paths:
        - .

        - name: Generate_project_files
          run: cmake -B ${{github.workspace}}/build ${{github.workspace}}


    Build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

      paths:
        - .
        - name: Compile
          run: cmake --build ${{github.workspace}}/build

  Execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    paths:
      - .

      - name: Run program
        run: ${{github.workspace}}/build/izip -v

      - name: Run tests
        run: ${{github.workspace}}/build/test

  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    paths:
      - .

      - name: Run tests
        run: ${{github.workspace}}/build/test

